const seedGroups=[
 {id:1,name:"Kid's Box Starter",level:"Starter",age:"5–6 лет",topic:"Hello!",url:"",cover:"",series:"Kid’s\nBox",num:"S",colors:["#f7a512","#ee5b1b"],icon:"✦"},
 {id:2,name:"Kid's Box 1",level:"A1",age:"6–7 лет",topic:"Toys",url:"",cover:"",series:"Kid’s\nBox",num:"1",colors:["#26aa69","#087043"],icon:"♧"},
 {id:3,name:"Academy Stars 1",level:"A1",age:"7–8 лет",topic:"All about me",url:"",cover:"",series:"Academy\nStars",num:"1",colors:["#e43b3d","#8c182c"],icon:"★"},
 {id:4,name:"Go Getter 1",level:"A1",age:"10–11 лет",topic:"My day",url:"",cover:"",series:"Go\nGetter",num:"1",colors:["#e82a35","#89132d"],icon:"◒"},
 {id:5,name:"Go Getter 2",level:"A1",age:"11–12 лет",topic:"Around town",url:"",cover:"",series:"Go\nGetter",num:"2",colors:["#16a7d6","#076193"],icon:"◇"},
 {id:6,name:"Go Getter 3",level:"A2",age:"12–13 лет",topic:"Film making",url:"",cover:"",series:"Go\nGetter",num:"3",colors:["#ef8610","#d2400d"],icon:"◉"},
 {id:7,name:"Go Getter 4",level:"A2",age:"13–14 лет",topic:"Adventure",url:"",cover:"",series:"Go\nGetter",num:"4",colors:["#7252bc","#332071"],icon:"✦"},
 {id:8,name:"Own It! 2",level:"B1",age:"14–15 лет",topic:"Communication",url:"",cover:"",series:"Own It!",num:"2",colors:["#ef9c3f","#bd3435"],icon:"✎"},
 {id:9,name:"Own It! 3",level:"B1",age:"15–16 лет",topic:"Challenges",url:"",cover:"",series:"Own It!",num:"3",colors:["#ca417c","#593075"],icon:"◎"},
 {id:10,name:"Own It! 4",level:"B2",age:"16+ лет",topic:"The future",url:"",cover:"",series:"Own It!",num:"4",colors:["#55a85e","#17654c"],icon:"⌁"}
];
const seedResources=[
 {id:101,title:"Teacher's Book — Unit 1",kind:"book",level:"A1",url:"https://example.com",note:"Книга учителя и дополнительные задания"},
 {id:102,title:"Grammar Practice",kind:"pdf",level:"A2",url:"https://example.com",note:"Рабочие листы для печати"},
 {id:103,title:"Vocabulary Games",kind:"link",level:"B1",url:"https://example.com",note:"Интерактивные игры для урока"}
];
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const fileDB=new Promise((resolve,reject)=>{const req=indexedDB.open('raduga-files',1);req.onupgradeneeded=()=>req.result.createObjectStore('files');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
async function saveFile(id,file){const db=await fileDB;return new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,String(id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function getFile(id){const db=await fileDB;return new Promise((resolve,reject)=>{const req=db.transaction('files').objectStore('files').get(String(id));req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function deleteFile(id){const db=await fileDB;return new Promise(resolve=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').delete(String(id));tx.oncomplete=resolve})}
let groups=load('raduga-groups',seedGroups),resources=load('raduga-resources',seedResources),favorites=load('raduga-favorites',[]),level='all',resourceKind='all',examSection='all',view='oge';
let tasks=load('raduga-tasks',[]),examDate=localStorage.getItem('raduga-exam-date')||'',taskStatus='all',pendingDeleteId=null;
let dayTasks=load('raduga-day-tasks',[{id:1,title:'Подготовить материалы к урокам',done:false},{id:2,title:'Проверить домашние задания',done:false}]);
let lessons=load('raduga-lessons',[]),scheduleStart=startOfWeek(new Date()),miniDate=new Date();
resources=resources.map(r=>(r.course==='oge'&&(r.section||'general')==='general')?{...r,course:'general'}:r);localStorage.setItem('raduga-resources',JSON.stringify(resources));
resources=resources.map(r=>({...r,collection:r.collection||'library'}));localStorage.setItem('raduga-resources',JSON.stringify(resources));
groups=groups.map(g=>{const go=/^go\s*getter/i.test(String(g.series||''))||/^Go Getter/.test(g.name);const own=/^Own(?: It!)? [234]$/.test(g.name);return {...g,series:go?'Go\nGetter':own?'Own It!':g.series,name:own?g.name.replace(/^Own(?: It!)? /,'Own It! '):g.name}});localStorage.setItem('raduga-groups',JSON.stringify(groups));
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const persist=()=>{localStorage.setItem('raduga-groups',JSON.stringify(groups));localStorage.setItem('raduga-resources',JSON.stringify(resources));localStorage.setItem('raduga-favorites',JSON.stringify(favorites));localStorage.setItem('raduga-tasks',JSON.stringify(tasks));localStorage.setItem('raduga-exam-date',examDate);localStorage.setItem('raduga-day-tasks',JSON.stringify(dayTasks));localStorage.setItem('raduga-lessons',JSON.stringify(lessons))};
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
function validUrl(url){if(!url)return false;try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)}catch{return false}}
function normalizeUrl(value=''){let url=String(value).trim();const markdown=url.match(/^\[[^\]]*\]\((https?:\/\/[^)]+)\)$/);if(markdown)url=markdown[1];if(url&&!/^https?:\/\//i.test(url))url='https://'+url;return url}
function renderGroups(){const q=$('#search').value.trim().toLowerCase();const shown=groups.filter(g=>(level==='all'||g.level===level)&&[g.name,g.topic,g.level].join(' ').toLowerCase().includes(q));$('#count').textContent=`${shown.length} ${shown.length===1?'группа':shown.length<5?'группы':'групп'}`;$('#cards').innerHTML=shown.length?shown.map(g=>{const image=validUrl(g.cover)?`background-image:linear-gradient(#0013,#0013),url('${esc(g.cover)}')`:'';return `<article class="card" data-id="${g.id}"><div class="cover ${image?'has-image':''}" style="--c1:${g.colors?.[0]||'#168b68'};--c2:${g.colors?.[1]||'#075141'};${image}"><strong>${esc(g.series||g.name).replace(/\n/g,'<br>')}</strong><small>${esc(g.icon||'✦')}</small><em>${esc(g.num||g.level)}</em></div><button class="menu-card" data-action="menu">•••</button><div class="card-menu hidden"><button data-action="edit">Изменить</button><button class="delete" data-action="delete">Удалить</button></div><div class="card-body"><h2>${esc(g.name)}</h2><p class="meta">${esc(g.age)} <b>${esc(g.level)}</b></p><p class="topic">Тема сейчас: ${esc(g.topic||'Не указана')}</p><div class="tags"><button class="tag" data-action="resources" data-kind="pdf">PDF</button><button class="tag" data-action="resources" data-kind="book">BOOK</button><button class="tag" data-action="resources" data-kind="link">LINKS</button></div><div class="actions"><button class="open-card" data-action="open">${validUrl(g.url)?'Открыть группу ↗':'Добавить ссылку ＋'}</button><button class="mini ${favorites.includes(g.id)?'saved':''}" data-action="favorite">${favorites.includes(g.id)?'♥':'♡'}</button></div></div></article>`}).join(''):'<div class="empty">Ничего не найдено. Добавьте первую группу или измените фильтр.</div>'}
function renderExamBlocks(){const oge=[['speaking','◯','Устная часть','Задания и тренажёры'],['listening','♫','Аудирование','Аудио и практика'],['reading','▱','Чтение','Тексты и задания'],['grammar','✎','Грамматика и лексика','Правила и практика'],['writing','✉','Письмо','Шаблоны и критерии']],vpr=[['grade4','▱','ВПР 4 класс','Материалы и задания для подготовки'],['grade5','▤','ВПР 5 класс','Материалы и задания для подготовки'],['grade6','✎','ВПР 6 класс','Материалы и задания для подготовки'],['grade7','▥','ВПР 7 класс','Материалы и задания для подготовки'],['grade8','◇','ВПР 8 класс','Материалы и задания для подготовки']];const items=view==='vpr'?vpr:oge;$('#examBlocks').innerHTML=items.map(x=>`<button class="${examSection===x[0]?'active':''}" data-section="${x[0]}"><i>${x[1]}</i><span><strong>${x[2]}</strong><small>${x[3]}</small></span><b>→</b></button>`).join('')}
function renderResources(){const q=$('#search').value.trim().toLowerCase();const examView=['oge','vpr'].includes(view),collectionOk=r=>view==='library'?(r.collection||'library')==='library':view==='materials'?r.collection==='materials':true;const shown=resources.filter(r=>(resourceKind==='all'||r.kind===resourceKind)&&collectionOk(r)&&(!examView||r.course===view)&&(examSection==='all'||(r.section||'general')===examSection)&&[r.title,r.note,r.level].join(' ').toLowerCase().includes(q));const icons={book:'▱',pdf:'PDF',link:'↗',lesson:'☷',presentation:'▣',cards:'▤',game:'✦',worksheet:'▧'};$('#resources').innerHTML=shown.length?shown.map(r=>{const url=normalizeUrl(r.url),source=r.fileId?'Файл на компьютере':validUrl(url)?(url.includes('yandex.')?'Яндекс Диск':'Внешняя ссылка'):'Ссылка не добавлена';return `<article class="resource" data-id="${esc(r.id)}" data-kind="${r.kind}"><div class="resource-icon">${icons[r.kind]||'▤'}</div><div><h3>${esc(r.title)}</h3><p>${esc(r.level)} · ${esc(r.note||'Без описания')}${r.fileName?`<br>📎 ${esc(r.fileName)}`:''}</p><span class="resource-source ${!r.fileId&&!validUrl(url)?'missing':''}">${source}</span></div><div class="resource-actions"><button data-r-action="open" title="Открыть материал">↗</button><button data-r-action="edit" title="Изменить">✎</button><button class="direct-delete" data-r-action="delete" title="Удалить материал">•••</button></div></article>`}).join(''):'<div class="empty">В этом разделе пока нет материалов. Нажмите «Добавить материал».</div>'}
function renderProgress(){const total=tasks.length,done=tasks.filter(t=>t.done).length,percent=total?Math.round(done/total*100):0;$('#progressPercent').textContent=`${percent}%`;$('#progressRing').style.background=`radial-gradient(circle,#062126 57%,transparent 59%),conic-gradient(#00d787 0 ${percent}%,#123c3b ${percent}%)`;$('#progressText').textContent=total?`${done} из ${total} задач выполнено. ${percent===100?'План завершён!': 'Продолжайте в том же духе.'}`:'Добавьте задачи в план подготовки.';if(examDate){const today=new Date();today.setHours(0,0,0,0);const days=Math.ceil((new Date(examDate+'T00:00:00')-today)/86400000);$('#examCountdown').textContent=days>0?`До экзамена ${days} ${days%10===1&&days%100!==11?'день':days%10>=2&&days%10<=4&&(days%100<10||days%100>=20)?'дня':'дней'}`:days===0?'Экзамен сегодня':`Экзамен прошёл ${Math.abs(days)} дн. назад`}else $('#examCountdown').textContent='Укажите дату экзамена'}
function renderTasks(){const names={grammar:'Грамматика и лексика',listening:'Аудирование',reading:'Чтение',writing:'Письмо',speaking:'Устная часть'};const shown=tasks.filter(t=>taskStatus==='all'||(taskStatus==='done'?t.done:!t.done)).sort((a,b)=>String(a.due).localeCompare(String(b.due)));$('#planScore').textContent=`${tasks.filter(t=>t.done).length} из ${tasks.length}`;$('#taskList').innerHTML=shown.length?shown.map(t=>{const r=resources.find(x=>String(x.id)===String(t.resourceId));return `<article class="task ${t.done?'done':''}" data-task-id="${t.id}"><button class="task-check" data-task-action="toggle" aria-label="Изменить статус">${t.done?'✓':''}</button><div><h3>${esc(t.title)}</h3><p>${names[t.section]||esc(t.section)} · до ${new Date(t.due+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</p>${r?`<a href="${esc(r.url)}" target="_blank" rel="noopener">Открыть материал ↗</a>`:''}</div><button class="task-edit" data-task-action="edit">✎</button><button class="task-delete" data-task-action="delete">×</button></article>`}).join(''):'<div class="plan-empty">Задач пока нет. Добавьте первый шаг подготовки.</div>';renderProgress()}
function openTaskForm(t){const f=$('#taskForm');f.reset();f.classList.remove('hidden');$('#taskResource').innerHTML='<option value="">Без материала</option>'+resources.filter(r=>(r.course||'general')==='oge'||(r.course||'general')==='general').map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join('');if(t)Object.keys(t).forEach(k=>{if(f.elements[k])f.elements[k].value=t[k]});else{f.elements.id.value='';f.elements.due.value=new Date(Date.now()+7*86400000).toISOString().slice(0,10)}f.elements.title.focus()}
function renderHome(){const now=new Date(),hour=now.getHours(),hello=hour<12?'Доброе утро':hour<18?'Добрый день':'Добрый вечер';$('#greeting').textContent=`${hello}, Marina!`;$('#todayDate').textContent=now.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long',year:'numeric'});const times=['10:00','12:30','15:00'];$('#lessonList').innerHTML=groups.slice(0,3).map((g,i)=>`<article><time>${times[i]}</time><div class="lesson-mark" style="--lesson-color:${g.colors?.[0]||'#00d884'}">${esc(g.num||g.level)}</div><div><h3>${esc(g.name)}</h3><p>${esc(g.topic||'Тема не указана')} · ${esc(g.level)}</p></div><button data-home-group="${g.id}">${validUrl(g.url)?'Открыть урок　↗':'Добавить ссылку　＋'}</button></article>`).join('');renderDayTasks();const recent=resources.slice(0,3),icons={book:'▱',pdf:'PDF',link:'↗',lesson:'☷',presentation:'▣',cards:'▤',game:'✦',worksheet:'▧'};$('#recentResources').innerHTML=recent.length?recent.map(r=>`<button data-home-resource="${esc(r.id)}"><i>${icons[r.kind]||'▤'}</i><span><strong>${esc(r.title)}</strong><small>${r.collection==='materials'?'Собственная разработка':'Библиотека'} · ${esc(r.level)}</small></span><b>›</b></button>`).join(''):'<div class="home-empty">Добавьте первый материал</div>';const done=tasks.filter(t=>t.done).length,percent=tasks.length?Math.round(done/tasks.length*100):0;$('#quickProgress').textContent=`Прогресс ${percent}%`;$('#homeStats').innerHTML=`<div><strong>${groups.length}</strong><span>групп</span></div><div><strong>${resources.length}</strong><span>материалов</span></div><div><strong>${dayTasks.filter(t=>!t.done).length}</strong><span>задач сегодня</span></div><div><strong>${percent}%</strong><span>план ОГЭ</span></div>`}
function renderDayTasks(){$('#dayTasks').innerHTML=dayTasks.length?dayTasks.map(t=>`<div class="day-task ${t.done?'done':''}" data-day-id="${t.id}"><button data-day-action="toggle">${t.done?'✓':''}</button><span>${esc(t.title)}</span><button data-day-action="delete">×</button></div>`).join(''):'<div class="home-empty">На сегодня всё выполнено ✦</div>'}
function startOfWeek(date){const d=new Date(date),day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return d}function isoDate(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function renderSchedule(){const days=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'],today=isoDate(new Date());$('#weekHead').innerHTML='<div></div>'+days.map((name,i)=>{const d=addDays(scheduleStart,i);return `<button class="${isoDate(d)===today?'today':''}" data-schedule-date="${isoDate(d)}"><strong>${name}</strong><span>${d.getDate()} ${d.toLocaleDateString('ru-RU',{month:'short'}).replace('.','')}</span></button>`}).join('');$('#timeColumn').innerHTML=Array.from({length:13},(_,i)=>`<span>${String(i+8).padStart(2,'0')}:00</span>`).join('');$('#weekGrid').innerHTML='<div class="grid-lines">'+Array.from({length:7},()=>'<i></i>').join('')+'</div>'+lessons.filter(l=>{const d=new Date(l.date+'T00:00:00');return d>=scheduleStart&&d<addDays(scheduleStart,7)}).map(l=>{const g=groups.find(x=>String(x.id)===String(l.groupId)),date=new Date(l.date+'T00:00:00'),day=(date.getDay()+6)%7,[h,m]=l.time.split(':').map(Number),top=((h-8)*60+m)/780*100,height=Number(l.duration)/780*100;return `<button class="lesson-event" data-lesson-id="${l.id}" style="--day:${day};--top:${top}%;--height:${height}%;--event-color:${l.color}"><strong>${esc(g?.name||'Группа')}</strong><span>${esc(l.time)} – ${endTime(l.time,l.duration)}</span>${l.note?`<small>${esc(l.note)}</small>`:''}</button>`}).join('');renderMiniCalendar();$('#scheduleGroupList').innerHTML=groups.slice(0,6).map((g,i)=>`<div><i style="background:${g.colors?.[0]||'#00d884'}"></i><span><strong>${esc(g.name)}</strong><small>${esc(g.age)} · ${esc(g.level)}</small></span><b>${lessons.filter(l=>String(l.groupId)===String(g.id)).length}</b></div>`).join('')}
function endTime(time,duration){const [h,m]=time.split(':').map(Number),total=h*60+m+Number(duration);return `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function renderMiniCalendar(){const y=miniDate.getFullYear(),m=miniDate.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,count=new Date(y,m+1,0).getDate(),today=isoDate(new Date());$('#miniMonth').textContent=miniDate.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});$('#miniDays').innerHTML=Array.from({length:start},()=>'<span></span>').join('')+Array.from({length:count},(_,i)=>{const d=new Date(y,m,i+1),iso=isoDate(d),has=lessons.some(l=>l.date===iso);return `<button class="${iso===today?'today':''} ${has?'has-lesson':''}" data-mini-date="${iso}">${i+1}</button>`}).join('')}
function openLessonForm(lesson,date){const f=$('#lessonForm');f.reset();$('#lessonGroup').innerHTML=groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('');$('#lessonModalTitle').textContent=lesson?'Редактировать занятие':'Новое занятие';$('#deleteLesson').classList.toggle('hidden',!lesson);if(lesson)Object.keys(lesson).forEach(k=>{if(f.elements[k])f.elements[k].value=lesson[k]});else{f.elements.id.value='';f.elements.date.value=date||isoDate(new Date());f.elements.time.value='10:00'}$('#lessonDialog').showModal()}
function showView(next){view=next;examSection='all';const isHome=next==='home',isSchedule=next==='schedule',isResource=['library','materials','oge','vpr'].includes(next);$('#homeView').classList.toggle('hidden',!isHome);$('#scheduleView').classList.toggle('hidden',!isSchedule);$('#groupView').classList.toggle('hidden',isHome||isSchedule||isResource);$('#resourceView').classList.toggle('hidden',isHome||isSchedule||!isResource);$('#examBlocks').classList.toggle('hidden',!['oge','vpr'].includes(next));const labels={home:['Главная','Ваш рабочий стол на сегодня.'],schedule:['Расписание','Все занятия и события в одном месте.'],groups:['Мои группы','Ученики, учебники и материалы — всё необходимое для урока в одном месте.'],library:['Библиотека','Книги, PDF и полезные ссылки для ваших занятий.'],materials:['Материалы','Ваша личная коллекция ресурсов для уроков.'],levels:['Уровни','Все группы, распределённые по уровням.'],oge:['Подготовка к ОГЭ','Материалы и ссылки для подготовки к экзамену.'],vpr:['Подготовка к ВПР','Материалы и ссылки для подготовки к ВПР.']};$('#pageTitle').textContent=labels[next]?.[0]||'Радуга';$('#pageSubtitle').textContent=labels[next]?.[1]||'';$('#addBtn').classList.toggle('hidden',isHome||isSchedule);$('#addBtn').innerHTML=isResource?'<span>＋</span> Добавить материал':'<span>＋</span> Добавить группу';if(next==='levels'){view='groups';$('#groupView').classList.remove('hidden');$('#resourceView').classList.add('hidden')}if(isHome)renderHome();else if(isSchedule)renderSchedule();else if(isResource){renderExamBlocks();renderResources()}else renderGroups();$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===next));closeMobile()}
function openGroupForm(g){const f=$('#groupForm');f.reset();$('#groupModalTitle').textContent=g?'Редактировать группу':'Новая группа';if(g)Object.keys(g).forEach(k=>{if(f.elements[k])f.elements[k].value=g[k]});else f.elements.id.value='';$('#groupDialog').showModal()}
function openResourceForm(r){const f=$('#resourceForm');f.reset();$('#selectedFile').textContent=r?.fileName?`Сохранён: ${r.fileName}`:'Файл не выбран';$('#resourceModalTitle').textContent=r?'Редактировать материал':'Новый материал';if(r)Object.keys(r).forEach(k=>{if(f.elements[k]&&k!=='file')f.elements[k].value=r[k]});else{f.elements.id.value='';f.elements.collection.value=view==='materials'?'materials':'library';if(['oge','vpr'].includes(view))f.elements.course.value=view;if(examSection!=='all')f.elements.section.value=examSection;else if(view==='oge')f.elements.section.value='oge_general';else if(view==='vpr')f.elements.section.value='grade4'}$('#resourceDialog').showModal()}
$('#groupForm').addEventListener('submit',e=>{e.preventDefault();if(e.submitter?.value==='cancel'){ $('#groupDialog').close();return }const f=e.currentTarget,d=Object.fromEntries(new FormData(f));const old=groups.find(g=>String(g.id)===d.id);if(old)Object.assign(old,d);else groups.unshift({...d,id:Date.now(),series:d.name,num:d.level,colors:['#0cc57b','#005f45'],icon:'✦'});persist();renderGroups();$('#groupDialog').close();toast('Группа сохранена')});
$('#resourceForm').addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value==='cancel'){ $('#resourceDialog').close();return }const f=e.currentTarget,fd=new FormData(f),file=f.elements.file.files[0],old=resources.find(r=>String(r.id)===fd.get('id'));fd.set('url',normalizeUrl(fd.get('url')));if(!fd.get('url')&&!file&&!old?.fileId){toast('Добавьте ссылку Яндекс Диска или выберите файл');return}const d=Object.fromEntries(fd);delete d.file;const id=old?.id||Date.now();if(file){await saveFile(id,file);d.fileId=id;d.fileName=file.name;d.fileType=file.type}if(old)Object.assign(old,d);else resources.unshift({...d,id});persist();renderResources();$('#resourceDialog').close();toast(file?'Файл загружен и сохранён':'Материал сохранён')});
$('#cards').addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const card=btn.closest('.card'),id=Number(card.dataset.id),g=groups.find(x=>x.id===id),action=btn.dataset.action;if(action==='menu')card.querySelector('.card-menu').classList.toggle('hidden');if(action==='edit')openGroupForm(g);if(action==='delete'&&confirm(`Удалить группу «${g.name}»?`)){groups=groups.filter(x=>x.id!==id);persist();renderGroups();toast('Группа удалена')}if(action==='open'){validUrl(g.url)?window.open(g.url,'_blank','noopener'):openGroupForm(g)}if(action==='resources'){resourceKind=btn.dataset.kind;showView('library');$$('#resourceTabs button').forEach(x=>x.classList.toggle('active',x.dataset.kind===resourceKind));renderResources()}if(action==='favorite'){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];persist();renderGroups()}});
$('#resources').addEventListener('click',async e=>{const btn=e.target.closest('[data-r-action]');if(!btn)return;const card=btn.closest('.resource'),id=card.dataset.id,r=resources.find(x=>String(x.id)===String(id)),action=btn.dataset.rAction;if(!r){toast('Не удалось найти материал. Обновите страницу');return}if(action==='open'){const external=normalizeUrl(r.url);if(!r.fileId&&validUrl(external)){window.location.assign(external);return}if(r.fileId){const file=await getFile(r.fileId);if(file){const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.target='_blank';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}else toast('Локальный файл не найден')}else{toast('Сначала добавьте ссылку Яндекс Диска');openResourceForm(r)}}if(action==='edit')openResourceForm(r);if(action==='delete'){pendingDeleteId=String(r.id);$('#deleteMessage').textContent=`«${r.title}» будет удалён из библиотеки${r.fileId?' вместе с загруженным файлом':''}.`;$('#deleteDialog').showModal()}});
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)showView(b.dataset.view)});$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-level]');if(!b)return;level=b.dataset.level;$$('#filters button').forEach(x=>x.classList.toggle('active',x===b));renderGroups()});$('#resourceTabs').addEventListener('click',e=>{const b=e.target.closest('[data-kind]');if(!b)return;resourceKind=b.dataset.kind;$$('#resourceTabs button').forEach(x=>x.classList.toggle('active',x===b));renderResources()});$('#examBlocks').addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(!b)return;examSection=examSection===b.dataset.section?'all':b.dataset.section;renderExamBlocks();renderResources();$('#resources').scrollIntoView({behavior:'smooth',block:'start'})});
$('#search').addEventListener('input',()=>view==='groups'?renderGroups():renderResources());$('#addBtn').addEventListener('click',()=>view==='groups'?openGroupForm():openResourceForm());$('#addResourceBtn').addEventListener('click',()=>openResourceForm());$('#profileBtn').addEventListener('click',()=>$('#profilePopover').classList.toggle('hidden'));
$('#resourceForm').elements.file.addEventListener('change',e=>{$('#selectedFile').textContent=e.target.files[0]?.name||'Файл не выбран'});
$('#addLessonBtn').addEventListener('click',()=>openLessonForm());$('#closeLesson').addEventListener('click',()=>$('#lessonDialog').close());$('#cancelLesson').addEventListener('click',()=>$('#lessonDialog').close());$('#lessonForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),old=lessons.find(l=>String(l.id)===d.id);if(old)Object.assign(old,d);else lessons.push({...d,id:Date.now()});persist();renderSchedule();$('#lessonDialog').close();toast('Занятие сохранено')});$('#deleteLesson').addEventListener('click',()=>{const id=$('#lessonForm').elements.id.value;lessons=lessons.filter(l=>String(l.id)!==String(id));persist();renderSchedule();$('#lessonDialog').close();toast('Занятие удалено')});$('#weekGrid').addEventListener('click',e=>{const b=e.target.closest('[data-lesson-id]');if(!b)return;const lesson=lessons.find(l=>String(l.id)===b.dataset.lessonId);openLessonForm(lesson)});$('#weekHead').addEventListener('click',e=>{const b=e.target.closest('[data-schedule-date]');if(b)openLessonForm(null,b.dataset.scheduleDate)});$('#schedulePrev').addEventListener('click',()=>{scheduleStart=addDays(scheduleStart,-7);renderSchedule()});$('#scheduleNext').addEventListener('click',()=>{scheduleStart=addDays(scheduleStart,7);renderSchedule()});$('#scheduleToday').addEventListener('click',()=>{scheduleStart=startOfWeek(new Date());miniDate=new Date();renderSchedule()});$('#miniPrev').addEventListener('click',()=>{miniDate=new Date(miniDate.getFullYear(),miniDate.getMonth()-1,1);renderMiniCalendar()});$('#miniNext').addEventListener('click',()=>{miniDate=new Date(miniDate.getFullYear(),miniDate.getMonth()+1,1);renderMiniCalendar()});$('#miniDays').addEventListener('click',e=>{const b=e.target.closest('[data-mini-date]');if(!b)return;scheduleStart=startOfWeek(new Date(b.dataset.miniDate+'T00:00:00'));renderSchedule()});$('#scheduleAllGroups').addEventListener('click',()=>showView('groups'));$('#scheduleAddGroup').addEventListener('click',()=>openGroupForm());
$('#addDayTask').addEventListener('click',()=>{$('#dayTaskForm').classList.toggle('hidden');if(!$('#dayTaskForm').classList.contains('hidden'))$('#dayTaskInput').focus()});$('#dayTaskForm').addEventListener('submit',e=>{e.preventDefault();const title=$('#dayTaskInput').value.trim();if(title){dayTasks.push({id:Date.now(),title,done:false});persist();renderDayTasks();e.currentTarget.reset();e.currentTarget.classList.add('hidden')}});$('#dayTasks').addEventListener('click',e=>{const b=e.target.closest('[data-day-action]');if(!b)return;const id=Number(b.closest('[data-day-id]').dataset.dayId);if(b.dataset.dayAction==='toggle'){const t=dayTasks.find(x=>x.id===id);t.done=!t.done}else dayTasks=dayTasks.filter(x=>x.id!==id);persist();renderDayTasks();renderHome()});$('#allGroupsBtn').addEventListener('click',()=>showView('groups'));$('#allLibraryBtn').addEventListener('click',()=>showView('library'));$('#lessonList').addEventListener('click',e=>{const b=e.target.closest('[data-home-group]');if(!b)return;const g=groups.find(x=>String(x.id)===b.dataset.homeGroup);validUrl(g?.url)?window.location.assign(normalizeUrl(g.url)):openGroupForm(g)});$('#recentResources').addEventListener('click',e=>{const b=e.target.closest('[data-home-resource]');if(!b)return;const r=resources.find(x=>String(x.id)===b.dataset.homeResource);if(r){showView(r.collection==='materials'?'materials':'library');setTimeout(()=>document.querySelector(`.resource[data-id="${CSS.escape(String(r.id))}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),50)}});$('#quickActions').addEventListener('click',e=>{const b=e.target.closest('[data-quick]');if(!b)return;const action=b.dataset.quick;if(action==='add')openResourceForm();else showView(action)});
$('#cancelDelete').addEventListener('click',()=>{pendingDeleteId=null;$('#deleteDialog').close()});$('#confirmDelete').addEventListener('click',async()=>{const r=resources.find(x=>String(x.id)===String(pendingDeleteId));if(!r){toast('Материал уже удалён');$('#deleteDialog').close();return}if(r.fileId)await deleteFile(r.fileId);resources=resources.filter(x=>String(x.id)!==String(pendingDeleteId));tasks=tasks.map(t=>String(t.resourceId)===String(pendingDeleteId)?{...t,resourceId:''}:t);pendingDeleteId=null;persist();renderResources();renderProgress();$('#deleteDialog').close();toast('Материал удалён')});
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({groups,resources,favorites,tasks,examDate},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='raduga-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Резервная копия скачана')});$('#importInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);groups=d.groups||groups;resources=d.resources||resources;favorites=d.favorites||[];tasks=d.tasks||tasks;examDate=d.examDate||examDate;persist();renderGroups();renderResources();renderProgress();toast('Данные импортированы')}catch{toast('Не удалось прочитать файл')}};reader.readAsText(file)});
$('#planBtn').addEventListener('click',()=>{$('#examDate').value=examDate;$('#taskForm').classList.add('hidden');renderTasks();$('#planDialog').showModal()});$('#closePlan').addEventListener('click',()=>$('#planDialog').close());$('#newTaskBtn').addEventListener('click',()=>openTaskForm());$('#cancelTask').addEventListener('click',()=>$('#taskForm').classList.add('hidden'));$('#examDate').addEventListener('change',e=>{examDate=e.target.value;persist();renderProgress()});
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),old=tasks.find(t=>String(t.id)===d.id);if(old)Object.assign(old,d);else tasks.push({...d,id:Date.now(),done:false});persist();e.currentTarget.classList.add('hidden');renderTasks();toast('Задача сохранена')});
$('#taskList').addEventListener('click',e=>{const b=e.target.closest('[data-task-action]');if(!b)return;const id=Number(b.closest('.task').dataset.taskId),t=tasks.find(x=>x.id===id);if(b.dataset.taskAction==='toggle'){t.done=!t.done;persist();renderTasks()}if(b.dataset.taskAction==='edit')openTaskForm(t);if(b.dataset.taskAction==='delete'&&confirm(`Удалить задачу «${t.title}»?`)){tasks=tasks.filter(x=>x.id!==id);persist();renderTasks()}});$('#planFilters').addEventListener('click',e=>{const b=e.target.closest('[data-status]');if(!b)return;taskStatus=b.dataset.status;$$('#planFilters button').forEach(x=>x.classList.toggle('active',x===b));renderTasks()});
function closeMobile(){$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')}$('#openMenu').addEventListener('click',()=>{$('#sidebar').classList.add('open');$('#scrim').classList.add('show')});$('#closeMenu').addEventListener('click',closeMobile);$('#scrim').addEventListener('click',closeMobile);document.addEventListener('click',e=>{if(!e.target.closest('.profile')&&!e.target.closest('.popover'))$('#profilePopover').classList.add('hidden')});renderExamBlocks();renderResources();renderProgress();

if(matchMedia('(hover:hover) and (pointer:fine)').matches){let lastSpark=0,sparkIndex=0;const colors=['#20e79a','#54f5c1','#ffad55','#dffdf5'],cursor=document.createElement('i');cursor.className='magic-cursor';document.body.appendChild(cursor);document.addEventListener('pointermove',e=>{cursor.style.left=`${e.clientX}px`;cursor.style.top=`${e.clientY}px`;const now=performance.now();if(now-lastSpark<22)return;lastSpark=now;for(let n=0;n<2;n++){const spark=document.createElement('i'),angle=Math.random()*Math.PI*2,distance=12+Math.random()*25;spark.className=`magic-spark ${sparkIndex++%3===0?'star':''}`;spark.style.left=`${e.clientX+(Math.random()-.5)*7}px`;spark.style.top=`${e.clientY+(Math.random()-.5)*7}px`;spark.style.setProperty('--spark',colors[sparkIndex%colors.length]);spark.style.setProperty('--drift-x',`${Math.cos(angle)*distance}px`);spark.style.setProperty('--drift-y',`${Math.sin(angle)*distance+12}px`);document.body.appendChild(spark);spark.addEventListener('animationend',()=>spark.remove(),{once:true})}},{passive:true});document.addEventListener('pointerdown',()=>cursor.classList.add('active'));document.addEventListener('pointerup',()=>cursor.classList.remove('active'))}
