const seedGroups=[
 {id:1,name:"Kid's Box Starter",level:"Starter",age:"5–6 лет",topic:"Hello!",url:"",cover:"",series:"Kid’s\nBox",num:"S",colors:["#f7a512","#ee5b1b"],icon:"✦"},
 {id:2,name:"Kid's Box 1",level:"A1",age:"6–7 лет",topic:"Toys",url:"",cover:"",series:"Kid’s\nBox",num:"1",colors:["#26aa69","#087043"],icon:"♧"},
 {id:3,name:"Academy Stars 1",level:"A1",age:"7–8 лет",topic:"All about me",url:"",cover:"",series:"Academy\nStars",num:"1",colors:["#e43b3d","#8c182c"],icon:"★"},
 {id:4,name:"Go Getter 1",level:"A1",age:"10–11 лет",topic:"My day",url:"",cover:"",series:"Go\nGetter",num:"1",colors:["#e82a35","#89132d"],icon:"◒"},
 {id:5,name:"Go Getter 2",level:"A1",age:"11–12 лет",topic:"Around town",url:"",cover:"",series:"Go\nGetter",num:"2",colors:["#16a7d6","#076193"],icon:"◇"},
 {id:6,name:"Go Getter 3",level:"A2",age:"12–13 лет",topic:"Film making",url:"",cover:"",series:"Go\nGetter",num:"3",colors:["#ef8610","#d2400d"],icon:"◉"},
 {id:7,name:"Go Getter 4",level:"A2",age:"13–14 лет",topic:"Adventure",url:"",cover:"",series:"Go\nGetter",num:"4",colors:["#7252bc","#332071"],icon:"✦"},
 {id:8,name:"Own It! 2",level:"B1",age:"14–15 лет",topic:"Communication",url:"",cover:"",series:"Own It!",num:"2",colors:["#ef9c3f","#bd3435"],icon:"✎"},
 {id:9,name:"Own It! 3",level:"B1",age:"15–16 лет",topic:"Challenges",url:"",cover:"",series:"Own It!",num:"3",colors:["#ca417c","#593075"],icon:"◎"},
 {id:10,name:"Own It! 4",level:"B2",age:"16+ лет",topic:"The future",url:"",cover:"",series:"Own It!",num:"4",colors:["#55a85e","#17654c"],icon:"⌁"}
];
const seedResources=[
 {id:101,title:"Teacher's Book — Unit 1",kind:"book",level:"A1",url:"https://example.com",note:"Книга учителя и дополнительные задания"},
 {id:102,title:"Grammar Practice",kind:"pdf",level:"A2",url:"https://example.com",note:"Рабочие листы для печати"},
 {id:103,title:"Vocabulary Games",kind:"link",level:"B1",url:"https://example.com",note:"Интерактивные игры для урока"}
];
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const fileDB=new Promise((resolve,reject)=>{const req=indexedDB.open('raduga-files',1);req.onupgradeneeded=()=>req.result.createObjectStore('files');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
async function saveFile(id,file){const db=await fileDB;return new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,String(id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function getFile(id){const db=await fileDB;return new Promise((resolve,reject)=>{const req=db.transaction('files').objectStore('files').get(String(id));req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function deleteFile(id){const db=await fileDB;return new Promise(resolve=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').delete(String(id));tx.oncomplete=resolve})}
let groups=load('raduga-groups',seedGroups),resources=load('raduga-resources',seedResources),favorites=load('raduga-favorites',[]),level='all',resourceKind='all',examSection='all',view='oge';
let tasks=load('raduga-tasks',[]),examDate=localStorage.getItem('raduga-exam-date')||'',taskStatus='all',pendingDeleteId=null;
let dayTasks=load('raduga-day-tasks',[{id:1,title:'Подготовить материалы к урокам',done:false},{id:2,title:'Проверить домашние задания',done:false}]);
let students=load('raduga-students',[]);
let lessons=load('raduga-lessons',[]),scheduleStart=startOfWeek(new Date()),miniDate=new Date(),calendarView='week',selectedScheduleDate=new Date();
resources=resources.map(r=>(r.course==='oge'&&(r.section||'general')==='general')?{...r,course:'general'}:r);localStorage.setItem('raduga-resources',JSON.stringify(resources));
resources=resources.map(r=>({...r,collection:r.collection||'library'}));localStorage.setItem('raduga-resources',JSON.stringify(resources));
groups=groups.map(g=>{const go=/^go\s*getter/i.test(String(g.series||''))||/^Go Getter/.test(g.name);const own=/^Own(?: It!)? [234]$/.test(g.name);return {...g,series:go?'Go\nGetter':own?'Own It!':g.series,name:own?g.name.replace(/^Own(?: It!)? /,'Own It! '):g.name}});localStorage.setItem('raduga-groups',JSON.stringify(groups));
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const cloudSnapshot=()=>({groups:[...groups],students,resources,favorites,tasks,dayTasks,lessons,examDate});const persist=(immediate=false)=>{localStorage.setItem('raduga-groups',JSON.stringify(groups));localStorage.setItem('raduga-resources',JSON.stringify(resources));localStorage.setItem('raduga-favorites',JSON.stringify(favorites));localStorage.setItem('raduga-tasks',JSON.stringify(tasks));localStorage.setItem('raduga-exam-date',examDate);localStorage.setItem('raduga-day-tasks',JSON.stringify(dayTasks));localStorage.setItem('raduga-lessons',JSON.stringify(lessons));localStorage.setItem('raduga-students',JSON.stringify(students));window.firebaseSyncSave?.(cloudSnapshot(),immediate)};
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
function validUrl(url){if(!url)return false;try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)}catch{return false}}
function normalizeUrl(value=''){let url=String(value).trim();const markdown=url.match(/^\[[^\]]*\]\((https?:\/\/[^)]+)\)$/);if(markdown)url=markdown[1];if(url&&!/^https?:\/\//i.test(url))url='https://'+url;return url}
function renderGroups(){const q=$('#search').value.trim().toLowerCase();const shown=groups.filter(g=>(level==='all'||g.level===level)&&[g.name,g.topic,g.level].join(' ').toLowerCase().includes(q));$('#count').textContent=`${shown.length} ${shown.length===1?'группа':shown.length<5?'группы':'групп'}`;$('#cards').innerHTML=shown.length?shown.map(g=>{const image=validUrl(g.cover)?`background-image:linear-gradient(#0013,#0013),url('${esc(g.cover)}')`:'';return `<article class="card" data-id="${g.id}"><div class="cover ${image?'has-image':''}" style="--c1:${g.colors?.[0]||'#168b68'};--c2:${g.colors?.[1]||'#075141'};${image}"><strong>${esc(g.series||g.name).replace(/\n/g,'<br>')}</strong><small>${esc(g.icon||'✦')}</small><em>${esc(g.num||g.level)}</em></div><button class="menu-card" data-action="menu">•••</button><div class="card-menu hidden"><button data-action="edit">Изменить</button><button class="delete" data-action="delete">Удалить</button></div><div class="card-body"><h2>${esc(g.name)}</h2><p class="meta">${esc(g.age)} <b>${esc(g.level)}</b></p><p class="topic">Тема сейчас: ${esc(g.topic||'Не указана')}</p><div class="tags"><button class="tag" data-action="resources" data-kind="pdf">PDF</button><button class="tag" data-action="resources" data-kind="book">BOOK</button><button class="tag" data-action="resources" data-kind="link">LINKS</button></div><div class="actions"><button class="open-card" data-action="open">${validUrl(g.url)?'Открыть группу ↗':'Добавить ссылку ＋'}</button><button class="mini ${favorites.includes(g.id)?'saved':''}" data-action="favorite">${favorites.includes(g.id)?'♥':'♡'}</button></div></div></article>`}).join(''):'<div class="empty">Ничего не найдено. Добавьте первую группу или измените фильтр.</div>'}
function renderExamBlocks(){const oge=[['speaking','◯','Устная часть','Задания и тренажёры'],['listening','♫','Аудирование','Аудио и практика'],['reading','▱','Чтение','Тексты и задания'],['grammar','✎','Грамматика и лексика','Правила и практика'],['writing','✉','Письмо','Шаблоны и критерии']],vpr=[['grade4','▱','ВПР 4 класс','Материалы и задания для подготовки'],['grade5','▤','ВПР 5 класс','Материалы и задания для подготовки'],['grade6','✎','ВПР 6 класс','Материалы и задания для подготовки'],['grade7','▥','ВПР 7 класс','Материалы и задания для подготовки'],['grade8','◇','ВПР 8 класс','Материалы и задания для подготовки']];const items=view==='vpr'?vpr:oge;$('#examBlocks').innerHTML=items.map(x=>`<button class="${examSection===x[0]?'active':''}" data-section="${x[0]}"><i>${x[1]}</i><span><strong>${x[2]}</strong><small>${x[3]}</small></span><b>→</b></button>`).join('')}
function renderResources(){const q=$('#search').value.trim().toLowerCase();const examView=['oge','vpr'].includes(view),collectionOk=r=>view==='library'?(r.collection||'library')==='library':view==='materials'?r.collection==='materials':true;const shown=resources.filter(r=>(resourceKind==='all'||r.kind===resourceKind)&&collectionOk(r)&&(!examView||r.course===view)&&(examSection==='all'||(r.section||'general')===examSection)&&[r.title,r.note,r.level].join(' ').toLowerCase().includes(q));const icons={book:'▱',pdf:'PDF',link:'↗',lesson:'☷',presentation:'▣',cards:'▤',game:'✦',worksheet:'▧'};$('#resources').innerHTML=shown.length?shown.map(r=>{const url=normalizeUrl(r.url),source=r.fileId?'Файл на компьютере':validUrl(url)?(url.includes('yandex.')?'Яндекс Диск':'Внешняя ссылка'):'Ссылка не добавлена';return `<article class="resource" data-id="${esc(r.id)}" data-kind="${r.kind}"><div class="resource-icon">${icons[r.kind]||'▤'}</div><div><h3>${esc(r.title)}</h3><p>${esc(r.level)} · ${esc(r.note||'Без описания')}${r.fileName?`<br>📎 ${esc(r.fileName)}`:''}</p><span class="resource-source ${!r.fileId&&!validUrl(url)?'missing':''}">${source}</span></div><div class="resource-actions"><button data-r-action="open" title="Открыть материал">↗</button><button data-r-action="edit" title="Изменить">✎</button><button class="direct-delete" data-r-action="delete" title="Удалить материал">•••</button></div></article>`}).join(''):'<div class="empty">В этом разделе пока нет материалов. Нажмите «Добавить материал».</div>'}
function renderProgress(){const total=tasks.length,done=tasks.filter(t=>t.done).length,percent=total?Math.round(done/total*100):0;$('#progressPercent').textContent=`${percent}%`;$('#progressRing').style.background=`radial-gradient(circle,#062126 57%,transparent 59%),conic-gradient(#00d787 0 ${percent}%,#123c3b ${percent}%)`;$('#progressText').textContent=total?`${done} из ${total} задач выполнено. ${percent===100?'План завершён!': 'Продолжайте в том же духе.'}`:'Добавьте задачи в план подготовки.';if(examDate){const today=new Date();today.setHours(0,0,0,0);const days=Math.ceil((new Date(examDate+'T00:00:00')-today)/86400000);$('#examCountdown').textContent=days>0?`До экзамена ${days} ${days%10===1&&days%100!==11?'день':days%10>=2&&days%10<=4&&(days%100<10||days%100>=20)?'дня':'дней'}`:days===0?'Экзамен сегодня':`Экзамен прошёл ${Math.abs(days)} дн. назад`}else $('#examCountdown').textContent='Укажите дату экзамена'}
function renderTasks(){const names={grammar:'Грамматика и лексика',listening:'Аудирование',reading:'Чтение',writing:'Письмо',speaking:'Устная часть'};const shown=tasks.filter(t=>taskStatus==='all'||(taskStatus==='done'?t.done:!t.done)).sort((a,b)=>String(a.due).localeCompare(String(b.due)));$('#planScore').textContent=`${tasks.filter(t=>t.done).length} из ${tasks.length}`;$('#taskList').innerHTML=shown.length?shown.map(t=>{const r=resources.find(x=>String(x.id)===String(t.resourceId));return `<article class="task ${t.done?'done':''}" data-task-id="${t.id}"><button class="task-check" data-task-action="toggle" aria-label="Изменить статус">${t.done?'✓':''}</button><div><h3>${esc(t.title)}</h3><p>${names[t.section]||esc(t.section)} · до ${new Date(t.due+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</p>${r?`<a href="${esc(r.url)}" target="_blank" rel="noopener">Открыть материал ↗</a>`:''}</div><button class="task-edit" data-task-action="edit">✎</button><button class="task-delete" data-task-action="delete">×</button></article>`}).join(''):'<div class="plan-empty">Задач пока нет. Добавьте первый шаг подготовки.</div>';renderProgress()}
function openTaskForm(t){const f=$('#taskForm');f.reset();f.classList.remove('hidden');$('#taskResource').innerHTML='<option value="">Без материала</option>'+resources.filter(r=>(r.course||'general')==='oge'||(r.course||'general')==='general').map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join('');if(t)Object.keys(t).forEach(k=>{if(f.elements[k])f.elements[k].value=t[k]});else{f.elements.id.value='';f.elements.due.value=new Date(Date.now()+7*86400000).toISOString().slice(0,10)}f.elements.title.focus()}
function renderHome(){const now=new Date(),hour=now.getHours(),hello=hour<12?'Доброе утро':hour<18?'Добрый день':'Добрый вечер';$('#greeting').textContent=`${hello}, Marina!`;$('#todayDate').textContent=now.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long',year:'numeric'});const times=['10:00','12:30','15:00'];$('#lessonList').innerHTML=groups.slice(0,3).map((g,i)=>`<article><time>${times[i]}</time><div class="lesson-mark" style="--lesson-color:${g.colors?.[0]||'#00d884'}">${esc(g.num||g.level)}</div><div><h3>${esc(g.name)}</h3><p>${esc(g.topic||'Тема не указана')} · ${esc(g.level)}</p></div><button data-home-group="${g.id}">${validUrl(g.url)?'Открыть урок　↗':'Добавить ссылку　＋'}</button></article>`).join('');renderDayTasks();const recent=resources.slice(0,3),icons={book:'▱',pdf:'PDF',link:'↗',lesson:'☷',presentation:'▣',cards:'▤',game:'✦',worksheet:'▧'};$('#recentResources').innerHTML=recent.length?recent.map(r=>`<button data-home-resource="${esc(r.id)}"><i>${icons[r.kind]||'▤'}</i><span><strong>${esc(r.title)}</strong><small>${r.collection==='materials'?'Собственная разработка':'Библиотека'} · ${esc(r.level)}</small></span><b>›</b></button>`).join(''):'<div class="home-empty">Добавьте первый материал</div>';const done=tasks.filter(t=>t.done).length,percent=tasks.length?Math.round(done/tasks.length*100):0;$('#quickProgress').textContent=`Прогресс ${percent}%`;$('#homeStats').innerHTML=`<div><strong>${groups.length}</strong><span>групп</span></div><div><strong>${resources.length}</strong><span>материалов</span></div><div><strong>${dayTasks.filter(t=>!t.done).length}</strong><span>задач сегодня</span></div><div><strong>${percent}%</strong><span>план ОГЭ</span></div>`}
function renderDayTasks(){$('#dayTasks').innerHTML=dayTasks.length?dayTasks.map(t=>`<div class="day-task ${t.done?'done':''}" data-day-id="${t.id}"><button data-day-action="toggle">${t.done?'✓':''}</button><span>${esc(t.title)}</span><button data-day-action="delete">×</button></div>`).join(''):'<div class="home-empty">На сегодня всё выполнено ✦</div>'}
function startOfWeek(date){const d=new Date(date),day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return d}function isoDate(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function renderSchedule(){const days=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'],today=isoDate(new Date());$('#weekHead').innerHTML='<div></div>'+days.map((name,i)=>{const d=addDays(scheduleStart,i);return `<button class="${isoDate(d)===today?'today':''}" data-schedule-date="${isoDate(d)}"><strong>${name}</strong><span>${d.getDate()} ${d.toLocaleDateString('ru-RU',{month:'short'}).replace('.','')}</span></button>`}).join('');$('#timeColumn').innerHTML=Array.from({length:13},(_,i)=>`<span>${String(i+8).padStart(2,'0')}:00</span>`).join('');$('#weekGrid').innerHTML='<div class="grid-lines">'+Array.from({length:7},()=>'<i></i>').join('')+'</div>'+lessons.filter(l=>{const d=new Date(l.date+'T00:00:00');return d>=scheduleStart&&d<addDays(scheduleStart,7)}).map(l=>{const g=groups.find(x=>String(x.id)===String(l.groupId)),date=new Date(l.date+'T00:00:00'),day=(date.getDay()+6)%7,[h,m]=l.time.split(':').map(Number),top=((h-8)*60+m)/780*100,height=Number(l.duration)/780*100;return `<button class="lesson-event" data-lesson-id="${l.id}" style="--day:${day};--top:${top}%;--height:${height}%;--event-color:${l.color}"><strong>${esc(g?.name||'Группа')}</strong><span>${esc(l.time)} – ${endTime(l.time,l.duration)}</span>${l.note?`<small>${esc(l.note)}</small>`:''}</button>`}).join('');renderMiniCalendar();$('#scheduleGroupList').innerHTML=groups.slice(0,6).map((g,i)=>`<div><i style="background:${g.colors?.[0]||'#00d884'}"></i><span><strong>${esc(g.name)}</strong><small>${esc(g.age)} · ${esc(g.level)}</small></span><b>${lessons.filter(l=>String(l.groupId)===String(g.id)).length}</b></div>`).join('')}
function renderCalendarView(){if(calendarView==='week'){renderSchedule();return}const canvas=$('#calendarCanvas');if(calendarView==='day'){const date=selectedScheduleDate,iso=isoDate(date),items=lessons.filter(l=>l.date===iso).sort((a,b)=>a.time.localeCompare(b.time));canvas.innerHTML=`<div class="day-view-head"><button data-day-date="${iso}"><strong>${date.toLocaleDateString('ru-RU',{weekday:'long'})}</strong><span>${date.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}</span></button></div><div class="day-agenda">${items.length?items.map(l=>{const g=groups.find(x=>String(x.id)===String(l.groupId));return `<button data-lesson-id="${l.id}" style="--event-color:${l.color}"><time>${l.time}<small>${endTime(l.time,l.duration)}</small></time><i></i><span><strong>${esc(g?.name||'Группа')}</strong><small>${esc(l.note||g?.topic||'Занятие')}</small></span><b>›</b></button>`}).join(''):`<div class="calendar-empty"><strong>На этот день занятий нет</strong><button data-add-on-date="${iso}">＋ Добавить занятие</button></div>`}</div>`}else{const y=selectedScheduleDate.getFullYear(),m=selectedScheduleDate.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,count=new Date(y,m+1,0).getDate();canvas.innerHTML=`<div class="month-view-head"><h3>${selectedScheduleDate.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}</h3></div><div class="month-weekdays">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<span>${x}</span>`).join('')}</div><div class="month-grid">${Array.from({length:offset},()=>'<div class="outside"></div>').join('')}${Array.from({length:count},(_,i)=>{const date=new Date(y,m,i+1),iso=isoDate(date),items=lessons.filter(l=>l.date===iso);return `<button class="month-day ${iso===isoDate(new Date())?'today':''}" data-month-date="${iso}"><b>${i+1}</b>${items.slice(0,3).map(l=>{const g=groups.find(x=>String(x.id)===String(l.groupId));return `<span style="--event-color:${l.color}">${l.time} ${esc(g?.name||'Группа')}</span>`}).join('')}${items.length>3?`<small>+ ещё ${items.length-3}</small>`:''}</button>`}).join('')}</div>`}renderMiniCalendar();$('#scheduleGroupList').innerHTML=groups.slice(0,6).map(g=>`<div><i style="background:${g.colors?.[0]||'#00d884'}"></i><span><strong>${esc(g.name)}</strong><small>${esc(g.age)} · ${esc(g.level)}</small></span><b>${lessons.filter(l=>String(l.groupId)===String(g.id)).length}</b></div>`).join('')}
function endTime(time,duration){const [h,m]=time.split(':').map(Number),total=h*60+m+Number(duration);return `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function renderMiniCalendar(){const y=miniDate.getFullYear(),m=miniDate.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,count=new Date(y,m+1,0).getDate(),today=isoDate(new Date());$('#miniMonth').textContent=miniDate.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});$('#miniDays').innerHTML=Array.from({length:start},()=>'<span></span>').join('')+Array.from({length:count},(_,i)=>{const d=new Date(y,m,i+1),iso=isoDate(d),has=lessons.some(l=>l.date===iso);return `<button class="${iso===today?'today':''} ${has?'has-lesson':''}" data-mini-date="${iso}">${i+1}</button>`}).join('')}
function openLessonForm(lesson,date){const f=$('#lessonForm');f.reset();$('#lessonGroup').innerHTML=groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('');$('#lessonModalTitle').textContent=lesson?'Редактировать занятие':'Новое занятие';$('#deleteLesson').classList.toggle('hidden',!lesson);if(lesson)Object.keys(lesson).forEach(k=>{if(f.elements[k])f.elements[k].value=lesson[k]});else{f.elements.id.value='';f.elements.date.value=date||isoDate(new Date());f.elements.time.value='10:00'}$('#lessonDialog').showModal()}
function showView(next){view=next;examSection='all';const isHome=next==='home',isSchedule=next==='schedule',isResource=['library','materials','oge','vpr'].includes(next);$('#homeView').classList.toggle('hidden',!isHome);$('#scheduleView').classList.toggle('hidden',!isSchedule);$('#groupView').classList.toggle('hidden',isHome||isSchedule||isResource);$('#resourceView').classList.toggle('hidden',isHome||isSchedule||!isResource);$('#examBlocks').classList.toggle('hidden',!['oge','vpr'].includes(next));const labels={home:['Главная','Ваш рабочий стол на сегодня.'],schedule:['Расписание','Все занятия и события в одном месте.'],groups:['Мои группы','Ученики, учебники и материалы — всё необходимое для урока в одном месте.'],library:['Библиотека','Книги, PDF и полезные ссылки для ваших занятий.'],materials:['Материалы','Ваша личная коллекция ресурсов для уроков.'],levels:['Уровни','Все группы, распределённые по уровням.'],oge:['Подготовка к ОГЭ','Материалы и ссылки для подготовки к экзамену.'],vpr:['Подготовка к ВПР','Материалы и ссылки для подготовки к ВПР.']};$('#pageTitle').textContent=labels[next]?.[0]||'Радуга';$('#pageSubtitle').textContent=labels[next]?.[1]||'';$('#addBtn').classList.toggle('hidden',isHome||isSchedule);$('#addBtn').innerHTML=isResource?'<span>＋</span> Добавить материал':'<span>＋</span> Добавить группу';if(next==='levels'){view='groups';$('#groupView').classList.remove('hidden');$('#resourceView').classList.add('hidden')}if(isHome)renderHome();else if(isSchedule)renderSchedule();else if(isResource){renderExamBlocks();renderResources()}else renderGroups();$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===next));closeMobile()}
function openGroupForm(g){const f=$('#groupForm');f.reset();$('#groupModalTitle').textContent=g?'Редактировать группу':'Новая группа';if(g)Object.keys(g).forEach(k=>{if(f.elements[k])f.elements[k].value=g[k]});else f.elements.id.value='';$('#groupDialog').showModal()}
function openResourceForm(r){const f=$('#resourceForm');f.reset();$('#selectedFile').textContent=r?.fileName?`Сохранён: ${r.fileName}`:'Файл не выбран';$('#resourceModalTitle').textContent=r?'Редактировать материал':'Новый материал';if(r)Object.keys(r).forEach(k=>{if(f.elements[k]&&k!=='file')f.elements[k].value=r[k]});else{f.elements.id.value='';f.elements.collection.value=view==='materials'?'materials':'library';if(['oge','vpr'].includes(view))f.elements.course.value=view;if(examSection!=='all')f.elements.section.value=examSection;else if(view==='oge')f.elements.section.value='oge_general';else if(view==='vpr')f.elements.section.value='grade4'}$('#resourceDialog').showModal()}
$('#groupForm').addEventListener('submit',e=>{e.preventDefault();if(e.submitter?.value==='cancel'){ $('#groupDialog').close();return }const f=e.currentTarget,d=Object.fromEntries(new FormData(f));const old=groups.find(g=>String(g.id)===d.id);if(old)Object.assign(old,d);else groups.unshift({...d,id:Date.now(),series:d.name,num:d.level,colors:['#0cc57b','#005f45'],icon:'✦'});persist();renderGroups();$('#groupDialog').close();toast('Группа сохранена')});
$('#resourceForm').addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value==='cancel'){ $('#resourceDialog').close();return }const f=e.currentTarget,fd=new FormData(f),file=f.elements.file.files[0],old=resources.find(r=>String(r.id)===fd.get('id'));fd.set('url',normalizeUrl(fd.get('url')));if(!fd.get('url')&&!file&&!old?.fileId){toast('Добавьте ссылку Яндекс Диска или выберите файл');return}const d=Object.fromEntries(fd);delete d.file;const id=old?.id||Date.now();if(file){await saveFile(id,file);d.fileId=id;d.fileName=file.name;d.fileType=file.type}if(old)Object.assign(old,d);else resources.unshift({...d,id});persist();renderResources();$('#resourceDialog').close();toast(file?'Файл загружен и сохранён':'Материал сохранён')});
$('#cards').addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const card=btn.closest('.card'),id=Number(card.dataset.id),g=groups.find(x=>x.id===id),action=btn.dataset.action;if(action==='menu')card.querySelector('.card-menu').classList.toggle('hidden');if(action==='edit')openGroupForm(g);if(action==='delete'&&confirm(`Удалить группу «${g.name}»?`)){groups=groups.filter(x=>x.id!==id);persist();renderGroups();toast('Группа удалена')}if(action==='open'){validUrl(g.url)?window.open(g.url,'_blank','noopener'):openGroupForm(g)}if(action==='resources'){resourceKind=btn.dataset.kind;showView('library');$$('#resourceTabs button').forEach(x=>x.classList.toggle('active',x.dataset.kind===resourceKind));renderResources()}if(action==='favorite'){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];persist();renderGroups()}});
$('#resources').addEventListener('click',async e=>{const btn=e.target.closest('[data-r-action]');if(!btn)return;const card=btn.closest('.resource'),id=card.dataset.id,r=resources.find(x=>String(x.id)===String(id)),action=btn.dataset.rAction;if(!r){toast('Не удалось найти материал. Обновите страницу');return}if(action==='open'){const external=normalizeUrl(r.url);if(!r.fileId&&validUrl(external)){window.location.assign(external);return}if(r.fileId){const file=await getFile(r.fileId);if(file){const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.target='_blank';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}else toast('Локальный файл не найден')}else{toast('Сначала добавьте ссылку Яндекс Диска');openResourceForm(r)}}if(action==='edit')openResourceForm(r);if(action==='delete'){pendingDeleteId=String(r.id);$('#deleteMessage').textContent=`«${r.title}» будет удалён из библиотеки${r.fileId?' вместе с загруженным файлом':''}.`;$('#deleteDialog').showModal()}});
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)showView(b.dataset.view)});$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-level]');if(!b)return;level=b.dataset.level;$$('#filters button').forEach(x=>x.classList.toggle('active',x===b));renderGroups()});$('#resourceTabs').addEventListener('click',e=>{const b=e.target.closest('[data-kind]');if(!b)return;resourceKind=b.dataset.kind;$$('#resourceTabs button').forEach(x=>x.classList.toggle('active',x===b));renderResources()});$('#examBlocks').addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(!b)return;examSection=examSection===b.dataset.section?'all':b.dataset.section;renderExamBlocks();renderResources();$('#resources').scrollIntoView({behavior:'smooth',block:'start'})});
$('#search').addEventListener('input',()=>view==='groups'?renderGroups():renderResources());$('#addBtn').addEventListener('click',()=>view==='groups'?openGroupForm():openResourceForm());$('#addResourceBtn').addEventListener('click',()=>openResourceForm());$('#profileBtn').addEventListener('click',()=>$('#profilePopover').classList.toggle('hidden'));
$('#resourceForm').elements.file.addEventListener('change',e=>{$('#selectedFile').textContent=e.target.files[0]?.name||'Файл не выбран'});
$('#scheduleViewTabs').addEventListener('click',e=>{const b=e.target.closest('[data-calendar-view]');if(!b)return;calendarView=b.dataset.calendarView;$$('#scheduleViewTabs button').forEach(x=>x.classList.toggle('active',x===b));renderCalendarView()});$('#calendarCanvas').addEventListener('click',e=>{const lessonButton=e.target.closest('[data-lesson-id]');if(lessonButton){const lesson=lessons.find(l=>String(l.id)===lessonButton.dataset.lessonId);openLessonForm(lesson);return}const monthDay=e.target.closest('[data-month-date]');if(monthDay){selectedScheduleDate=new Date(monthDay.dataset.monthDate+'T00:00:00');calendarView='day';$$('#scheduleViewTabs button').forEach(x=>x.classList.toggle('active',x.dataset.calendarView==='day'));renderCalendarView();return}const add=e.target.closest('[data-add-on-date]');if(add)openLessonForm(null,add.dataset.addOnDate)});
$('#addLessonBtn').addEventListener('click',()=>openLessonForm());$('#closeLesson').addEventListener('click',()=>$('#lessonDialog').close());$('#cancelLesson').addEventListener('click',()=>$('#lessonDialog').close());$('#lessonForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),old=lessons.find(l=>String(l.id)===d.id);if(old)Object.assign(old,d);else lessons.push({...d,id:Date.now()});persist();renderSchedule();$('#lessonDialog').close();toast('Занятие сохранено')});$('#deleteLesson').addEventListener('click',()=>{const id=String($('#lessonForm').elements.id.value).trim(),before=lessons.length;if(!id){toast('Не удалось определить занятие');return}lessons=lessons.filter(l=>String(l.id)!==id);if(lessons.length===before){toast('Занятие уже удалено');$('#lessonDialog').close();return}persist(true);renderCalendarView();renderHome();$('#lessonDialog').close();toast('Занятие удалено')});$('#weekGrid').addEventListener('click',e=>{const b=e.target.closest('[data-lesson-id]');if(!b)return;const lesson=lessons.find(l=>String(l.id)===b.dataset.lessonId);openLessonForm(lesson)});$('#weekHead').addEventListener('click',e=>{const b=e.target.closest('[data-schedule-date]');if(b)openLessonForm(null,b.dataset.scheduleDate)});$('#schedulePrev').addEventListener('click',()=>{scheduleStart=addDays(scheduleStart,-7);renderSchedule()});$('#scheduleNext').addEventListener('click',()=>{scheduleStart=addDays(scheduleStart,7);renderSchedule()});$('#scheduleToday').addEventListener('click',()=>{scheduleStart=startOfWeek(new Date());miniDate=new Date();renderSchedule()});$('#miniPrev').addEventListener('click',()=>{miniDate=new Date(miniDate.getFullYear(),miniDate.getMonth()-1,1);renderMiniCalendar()});$('#miniNext').addEventListener('click',()=>{miniDate=new Date(miniDate.getFullYear(),miniDate.getMonth()+1,1);renderMiniCalendar()});$('#miniDays').addEventListener('click',e=>{const b=e.target.closest('[data-mini-date]');if(!b)return;scheduleStart=startOfWeek(new Date(b.dataset.miniDate+'T00:00:00'));renderSchedule()});$('#scheduleAllGroups').addEventListener('click',()=>showView('groups'));$('#scheduleAddGroup').addEventListener('click',()=>openGroupForm());
$('#addDayTask').addEventListener('click',()=>{$('#dayTaskForm').classList.toggle('hidden');if(!$('#dayTaskForm').classList.contains('hidden'))$('#dayTaskInput').focus()});$('#dayTaskForm').addEventListener('submit',e=>{e.preventDefault();const title=$('#dayTaskInput').value.trim();if(title){dayTasks.push({id:Date.now(),title,done:false});persist();renderDayTasks();e.currentTarget.reset();e.currentTarget.classList.add('hidden')}});$('#dayTasks').addEventListener('click',e=>{const b=e.target.closest('[data-day-action]');if(!b)return;const id=Number(b.closest('[data-day-id]').dataset.dayId);if(b.dataset.dayAction==='toggle'){const t=dayTasks.find(x=>x.id===id);t.done=!t.done}else dayTasks=dayTasks.filter(x=>x.id!==id);persist();renderDayTasks();renderHome()});$('#allGroupsBtn').addEventListener('click',()=>showView('groups'));$('#allLibraryBtn').addEventListener('click',()=>showView('library'));$('#lessonList').addEventListener('click',e=>{const b=e.target.closest('[data-home-group]');if(!b)return;const g=groups.find(x=>String(x.id)===b.dataset.homeGroup);validUrl(g?.url)?window.location.assign(normalizeUrl(g.url)):openGroupForm(g)});$('#recentResources').addEventListener('click',e=>{const b=e.target.closest('[data-home-resource]');if(!b)return;const r=resources.find(x=>String(x.id)===b.dataset.homeResource);if(r){showView(r.collection==='materials'?'materials':'library');setTimeout(()=>document.querySelector(`.resource[data-id="${CSS.escape(String(r.id))}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),50)}});$('#quickActions').addEventListener('click',e=>{const b=e.target.closest('[data-quick]');if(!b)return;const action=b.dataset.quick;if(action==='add')openResourceForm();else showView(action)});
$('#cancelDelete').addEventListener('click',()=>{pendingDeleteId=null;$('#deleteDialog').close()});$('#confirmDelete').addEventListener('click',async()=>{const r=resources.find(x=>String(x.id)===String(pendingDeleteId));if(!r){toast('Материал уже удалён');$('#deleteDialog').close();return}if(r.fileId)await deleteFile(r.fileId);resources=resources.filter(x=>String(x.id)!==String(pendingDeleteId));tasks=tasks.map(t=>String(t.resourceId)===String(pendingDeleteId)?{...t,resourceId:''}:t);pendingDeleteId=null;persist();renderResources();renderProgress();$('#deleteDialog').close();toast('Материал удалён')});
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({groups,resources,favorites,tasks,examDate},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='raduga-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Резервная копия скачана')});$('#importInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);groups=d.groups||groups;resources=d.resources||resources;favorites=d.favorites||[];tasks=d.tasks||tasks;examDate=d.examDate||examDate;persist();renderGroups();renderResources();renderProgress();toast('Данные импортированы')}catch{toast('Не удалось прочитать файл')}};reader.readAsText(file)});
$('#planBtn').addEventListener('click',()=>{$('#examDate').value=examDate;$('#taskForm').classList.add('hidden');renderTasks();$('#planDialog').showModal()});$('#closePlan').addEventListener('click',()=>$('#planDialog').close());$('#newTaskBtn').addEventListener('click',()=>openTaskForm());$('#cancelTask').addEventListener('click',()=>$('#taskForm').classList.add('hidden'));$('#examDate').addEventListener('change',e=>{examDate=e.target.value;persist();renderProgress()});
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),old=tasks.find(t=>String(t.id)===d.id);if(old)Object.assign(old,d);else tasks.push({...d,id:Date.now(),done:false});persist();e.currentTarget.classList.add('hidden');renderTasks();toast('Задача сохранена')});
$('#taskList').addEventListener('click',e=>{const b=e.target.closest('[data-task-action]');if(!b)return;const id=Number(b.closest('.task').dataset.taskId),t=tasks.find(x=>x.id===id);if(b.dataset.taskAction==='toggle'){t.done=!t.done;persist();renderTasks()}if(b.dataset.taskAction==='edit')openTaskForm(t);if(b.dataset.taskAction==='delete'&&confirm(`Удалить задачу «${t.title}»?`)){tasks=tasks.filter(x=>x.id!==id);persist();renderTasks()}});$('#planFilters').addEventListener('click',e=>{const b=e.target.closest('[data-status]');if(!b)return;taskStatus=b.dataset.status;$$('#planFilters button').forEach(x=>x.classList.toggle('active',x===b));renderTasks()});
function closeMobile(){$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')}$('#openMenu').addEventListener('click',()=>{$('#sidebar').classList.add('open');$('#scrim').classList.add('show')});$('#closeMenu').addEventListener('click',closeMobile);$('#scrim').addEventListener('click',closeMobile);document.addEventListener('click',e=>{if(!e.target.closest('.profile')&&!e.target.closest('.popover'))$('#profilePopover').classList.add('hidden')});renderExamBlocks();renderResources();renderProgress();

if(matchMedia('(hover:hover) and (pointer:fine)').matches){let lastSpark=0,sparkIndex=0;const colors=['#20e79a','#54f5c1','#ffad55','#dffdf5'],cursor=document.createElement('i');cursor.className='magic-cursor';document.body.appendChild(cursor);document.addEventListener('pointermove',e=>{cursor.style.left=`${e.clientX}px`;cursor.style.top=`${e.clientY}px`;const now=performance.now();if(now-lastSpark<22)return;lastSpark=now;for(let n=0;n<2;n++){const spark=document.createElement('i'),angle=Math.random()*Math.PI*2,distance=12+Math.random()*25;spark.className=`magic-spark ${sparkIndex++%3===0?'star':''}`;spark.style.left=`${e.clientX+(Math.random()-.5)*7}px`;spark.style.top=`${e.clientY+(Math.random()-.5)*7}px`;spark.style.setProperty('--spark',colors[sparkIndex%colors.length]);spark.style.setProperty('--drift-x',`${Math.cos(angle)*distance}px`);spark.style.setProperty('--drift-y',`${Math.sin(angle)*distance+12}px`);document.body.appendChild(spark);spark.addEventListener('animationend',()=>spark.remove(),{once:true})}},{passive:true});document.addEventListener('pointerdown',()=>cursor.classList.add('active'));document.addEventListener('pointerup',()=>cursor.classList.remove('active'))}

// Единый раздел материалов: сохраняем старые записи из обеих коллекций.
resources=resources.map(r=>({...r,collection:'materials'}));persist();renderResources();
const showViewBase=showView;
showView=function(next){
  showViewBase(next==='library'?'materials':next);
  if(next==='library'||next==='materials'){
    $('#pageTitle').textContent='Материалы';
    $('#pageSubtitle').textContent='Книги, PDF, ссылки и ваши разработки в одном месте.';
  }
  if(next==='schedule'&&calendarView!=='week')renderCalendarView();
};
const openResourceFormBase=openResourceForm;
openResourceForm=function(resource){openResourceFormBase(resource);$('#resourceForm').elements.collection.value='materials'};

// Восстанавливаем недельную сетку после переключения с месяца или дня.
const renderScheduleBase=renderSchedule;
renderSchedule=function(){
  if(calendarView!=='week'){renderCalendarView();return}
  if(!$('#weekHead'))$('#calendarCanvas').innerHTML='<div class="week-head" id="weekHead"></div><div class="week-body"><div class="time-column" id="timeColumn"></div><div class="week-grid" id="weekGrid"></div></div>';
  renderScheduleBase();
};

function moveCalendar(direction){
  if(calendarView==='week')scheduleStart=addDays(scheduleStart,direction*7);
  else if(calendarView==='day')selectedScheduleDate=addDays(selectedScheduleDate,direction);
  else selectedScheduleDate=new Date(selectedScheduleDate.getFullYear(),selectedScheduleDate.getMonth()+direction,1);
  miniDate=new Date(selectedScheduleDate);
  renderCalendarView();
}
$('#schedulePrev').addEventListener('click',e=>{e.stopImmediatePropagation();moveCalendar(-1)},{capture:true});
$('#scheduleNext').addEventListener('click',e=>{e.stopImmediatePropagation();moveCalendar(1)},{capture:true});
$('#scheduleToday').addEventListener('click',e=>{e.stopImmediatePropagation();selectedScheduleDate=new Date();scheduleStart=startOfWeek(selectedScheduleDate);miniDate=new Date();renderCalendarView()},{capture:true});
$('#calendarCanvas').addEventListener('click',e=>{const day=e.target.closest('[data-schedule-date]');if(day)openLessonForm(null,day.dataset.scheduleDate)});
$('#miniDays').addEventListener('click',e=>{const day=e.target.closest('[data-mini-date]');if(!day||calendarView==='week')return;e.stopImmediatePropagation();selectedScheduleDate=new Date(day.dataset.miniDate+'T00:00:00');renderCalendarView()},{capture:true});

const themeIcons={system:'◐',dark:'☾',light:'☀'};
function setTheme(theme,announce=false){
  document.documentElement.dataset.theme=theme;
  document.documentElement.classList.toggle('theme-light',theme==='light'||(theme==='system'&&matchMedia('(prefers-color-scheme:light)').matches));
  localStorage.setItem('raduga-theme',theme);
  $('#themeIcon').textContent=themeIcons[theme];
  $$('#themeOptions [data-theme-choice]').forEach(button=>button.classList.toggle('active',button.dataset.themeChoice===theme));
  if(announce)toast(theme==='system'?'Тема следует за системой':theme==='light'?'Включена светлая тема':'Включена тёмная тема');
}
setTheme(localStorage.getItem('raduga-theme')||'system');
$('#themeBtn').addEventListener('click',e=>{e.stopPropagation();$('#profilePopover').classList.add('hidden');$('#themePopover').classList.toggle('hidden')});
$('#themeOptions').addEventListener('click',e=>{const button=e.target.closest('[data-theme-choice]');if(!button)return;setTheme(button.dataset.themeChoice,true);$('#themePopover').classList.add('hidden')});
document.addEventListener('click',e=>{if(!e.target.closest('#themePopover')&&!e.target.closest('#themeBtn'))$('#themePopover').classList.add('hidden')});
matchMedia('(prefers-color-scheme:light)').addEventListener('change',()=>{if((localStorage.getItem('raduga-theme')||'system')==='system')setTheme('system')});

// «Ссылки и Диск» фильтрует по наличию URL, а не по типу карточки.
renderResources=function(){
  const q=$('#search').value.trim().toLowerCase(),examView=['oge','vpr'].includes(view);
  const matchesKind=r=>resourceKind==='all'||(resourceKind==='link'?validUrl(normalizeUrl(r.url)):r.kind===resourceKind);
  const shown=resources.filter(r=>matchesKind(r)&&(!examView||r.course===view)&&(examSection==='all'||(r.section||'general')===examSection)&&[r.title,r.note,r.level].join(' ').toLowerCase().includes(q));
  const icons={book:'▱',pdf:'PDF',link:'↗',lesson:'☷',presentation:'▣',cards:'▤',game:'✦',worksheet:'▧'};
  $('#resources').innerHTML=shown.length?shown.map(r=>{
    const url=normalizeUrl(r.url),source=r.fileId?'Файл на компьютере':validUrl(url)?(url.includes('yandex.')?'Яндекс Диск':'Внешняя ссылка'):'Ссылка не добавлена';
    return `<article class="resource" data-id="${esc(r.id)}" data-kind="${r.kind}"><div class="resource-icon">${icons[r.kind]||'▤'}</div><div><h3>${esc(r.title)}</h3><p>${esc(r.level)} · ${esc(r.note||'Без описания')}${r.fileName?`<br>📎 ${esc(r.fileName)}`:''}</p><span class="resource-source ${!r.fileId&&!validUrl(url)?'missing':''}">${source}</span></div><div class="resource-actions"><button data-r-action="open" title="Открыть материал">↗</button><button data-r-action="edit" title="Изменить">✎</button><button class="direct-delete" data-r-action="delete" title="Удалить материал">•••</button></div></article>`;
  }).join(''):'<div class="empty">Материалов со ссылками пока нет.</div>';
};
renderResources();

let homeCalendarDate=new Date();
function renderHomeCalendar(){
  const y=homeCalendarDate.getFullYear(),m=homeCalendarDate.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,count=new Date(y,m+1,0).getDate(),today=isoDate(new Date());
  $('#homeCalendarTitle').textContent=homeCalendarDate.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});
  const previousCount=new Date(y,m,0).getDate(),cells=[];
  for(let i=offset-1;i>=0;i--)cells.push(`<span class="outside"><b>${previousCount-i}</b></span>`);
  for(let day=1;day<=count;day++){
    const date=new Date(y,m,day),iso=isoDate(date),items=lessons.filter(l=>l.date===iso).sort((a,b)=>a.time.localeCompare(b.time));
    cells.push(`<button class="${iso===today?'today':''} ${items.length?'has-lessons':''}" data-home-calendar-date="${iso}"><b>${day}</b>${items.slice(0,2).map(l=>{const g=groups.find(x=>String(x.id)===String(l.groupId));return `<span style="--event-color:${l.color}"><i></i>${l.time} ${esc(g?.name||'Группа')}</span>`}).join('')}${items.length>2?`<small>+ещё ${items.length-2}</small>`:''}</button>`);
  }
  const tail=(7-cells.length%7)%7;for(let day=1;day<=tail;day++)cells.push(`<span class="outside"><b>${day}</b></span>`);
  $('#homeCalendarGrid').innerHTML=cells.join('');
}
const renderHomeBase=renderHome;
renderHome=function(){renderHomeBase();renderHomeCalendar()};
$('#homeCalendarPrev').addEventListener('click',()=>{homeCalendarDate=new Date(homeCalendarDate.getFullYear(),homeCalendarDate.getMonth()-1,1);renderHomeCalendar()});
$('#homeCalendarNext').addEventListener('click',()=>{homeCalendarDate=new Date(homeCalendarDate.getFullYear(),homeCalendarDate.getMonth()+1,1);renderHomeCalendar()});
$('#homeCalendarToday').addEventListener('click',()=>{homeCalendarDate=new Date();renderHomeCalendar()});
$('#homeCalendarGrid').addEventListener('click',e=>{const day=e.target.closest('[data-home-calendar-date]');if(!day)return;selectedScheduleDate=new Date(day.dataset.homeCalendarDate+'T00:00:00');scheduleStart=startOfWeek(selectedScheduleDate);miniDate=new Date(selectedScheduleDate);calendarView='day';$$('#scheduleViewTabs button').forEach(button=>button.classList.toggle('active',button.dataset.calendarView==='day'));showView('schedule')});

function renderTodaySchedule(){
  const today=isoDate(new Date()),items=lessons.filter(lesson=>lesson.date===today).sort((a,b)=>a.time.localeCompare(b.time));
  $('#lessonList').innerHTML=items.length?items.map(lesson=>{
    const group=groups.find(item=>String(item.id)===String(lesson.groupId)),color=lesson.color||group?.colors?.[0]||'#00d884';
    return `<article><time>${esc(lesson.time)}<small>${endTime(lesson.time,lesson.duration)}</small></time><div class="lesson-mark" style="--lesson-color:${color}">${esc(group?.num||group?.level||'•')}</div><div><h3>${esc(group?.name||'Группа')}</h3><p>${esc(lesson.note||group?.topic||'Тема не указана')} · ${esc(group?.level||'')}</p></div><button data-home-lesson="${lesson.id}">Открыть занятие　›</button></article>`;
  }).join(''):'<div class="today-schedule-empty"><strong>На сегодня занятий нет</strong><span>Добавьте занятие в расписании.</span><button id="emptyTodaySchedule">＋ Добавить</button></div>';
}
const renderHomeDashboard=renderHome;
renderHome=function(){renderHomeDashboard();renderTodaySchedule()};
$('#lessonList').addEventListener('click',e=>{const button=e.target.closest('[data-home-lesson]');if(!button)return;const lesson=lessons.find(item=>String(item.id)===button.dataset.homeLesson);if(lesson)openLessonForm(lesson)});
$('#lessonList').addEventListener('click',e=>{if(e.target.closest('#emptyTodaySchedule'))openLessonForm(null,isoDate(new Date()))});
$('#allGroupsBtn').addEventListener('click',e=>{e.stopImmediatePropagation();selectedScheduleDate=new Date();scheduleStart=startOfWeek(selectedScheduleDate);calendarView='day';$$('#scheduleViewTabs button').forEach(button=>button.classList.toggle('active',button.dataset.calendarView==='day'));showView('schedule')},{capture:true});
$('#cards').addEventListener('click',e=>{const button=e.target.closest('[data-action="resources"]');if(!button)return;e.stopImmediatePropagation();resourceKind=button.dataset.kind;showView('materials');$$('#resourceTabs button').forEach(tab=>tab.classList.toggle('active',tab.dataset.kind===resourceKind));renderResources()},{capture:true});

function studentWord(count){const last=count%10,lastTwo=count%100;return last===1&&lastTwo!==11?'ученик':last>=2&&last<=4&&(lastTwo<12||lastTwo>14)?'ученика':'учеников'}
function renderStudents(){
  const q=$('#search').value.trim().toLowerCase(),shown=students.filter(student=>[student.name,student.age,student.level,student.book,student.homework,student.note].join(' ').toLowerCase().includes(q));
  $('#studentCount').textContent=`${shown.length} ${studentWord(shown.length)}`;
  $('#studentCards').innerHTML=shown.length?shown.map(student=>`<article class="student-card" data-student-id="${student.id}"><div class="student-avatar">${esc(student.name).trim().charAt(0).toUpperCase()||'•'}</div><div class="student-main"><div><h2>${esc(student.name)}</h2><span>${esc(student.age||'Возраст не указан')} · ${esc(student.level)}</span></div><section><small>УЧЕБНИК</small><strong>${esc(student.book)}</strong>${validUrl(normalizeUrl(student.url))?'<button data-student-action="open-book">Открыть учебник ↗</button>':''}</section><section class="student-homework"><small>ДОМАШНЕЕ ЗАДАНИЕ</small><p>${esc(student.homework||'Не задано')}</p></section>${student.note?`<p class="student-note">${esc(student.note)}</p>`:''}</div><div class="student-actions"><button data-student-action="edit" title="Изменить">✎</button><button data-student-action="delete" title="Удалить">×</button></div></article>`).join(''):'<div class="student-empty"><strong>Индивидуальных учеников пока нет</strong><span>Добавьте первого ученика и укажите его учебник.</span></div>';
}
function openStudentForm(student){const form=$('#studentForm');form.reset();$('#studentModalTitle').textContent=student?'Редактировать ученика':'Новый ученик';if(student)Object.keys(student).forEach(key=>{if(form.elements[key])form.elements[key].value=student[key]});else form.elements.id.value='';$('#studentDialog').showModal()}
const showViewBeforeStudents=showView;
showView=function(next){
  if(next!=='students'){showViewBeforeStudents(next);$('#studentView').classList.add('hidden');return}
  view='students';$('#homeView').classList.add('hidden');$('#scheduleView').classList.add('hidden');$('#groupView').classList.add('hidden');$('#resourceView').classList.add('hidden');$('#studentView').classList.remove('hidden');$('#pageTitle').textContent='Индивидуальные ученики';$('#pageSubtitle').textContent='Учебники, домашние задания и заметки для индивидуальных занятий.';$('#addBtn').classList.add('hidden');$$('#nav button').forEach(button=>button.classList.toggle('active',button.dataset.view==='students'));renderStudents();closeMobile();
};
$('#addStudentBtn').addEventListener('click',()=>openStudentForm());
$('#closeStudent').addEventListener('click',()=>$('#studentDialog').close());$('#cancelStudent').addEventListener('click',()=>$('#studentDialog').close());
$('#studentForm').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));data.url=normalizeUrl(data.url);const student=students.find(item=>String(item.id)===data.id);if(student)Object.assign(student,data);else students.unshift({...data,id:Date.now()});persist();renderStudents();$('#studentDialog').close();toast('Ученик сохранён')});
$('#studentCards').addEventListener('click',e=>{const button=e.target.closest('[data-student-action]');if(!button)return;const card=button.closest('[data-student-id]'),student=students.find(item=>String(item.id)===card.dataset.studentId);if(!student)return;if(button.dataset.studentAction==='edit')openStudentForm(student);if(button.dataset.studentAction==='open-book'&&validUrl(normalizeUrl(student.url)))window.location.assign(normalizeUrl(student.url));if(button.dataset.studentAction==='delete'&&confirm(`Удалить ученика «${student.name}»?`)){students=students.filter(item=>String(item.id)!==String(student.id));persist();renderStudents();toast('Ученик удалён')}});
$('#search').addEventListener('input',e=>{if(view!=='students')return;e.stopImmediatePropagation();renderStudents()},{capture:true});

// Restore the last open section after a page refresh.
const showViewPersistent=showView;
showView=function(next){
  const normalized=next==='library'?'materials':next==='levels'?'groups':next;
  showViewPersistent(normalized);
  localStorage.setItem('raduga-current-view',normalized);
};
const savedView=localStorage.getItem('raduga-current-view');
const availableViews=['home','schedule','groups','students','materials','oge','vpr'];
showView(availableViews.includes(savedView)?savedView:'oge');

// Individual students can be selected and edited in the same lesson form as groups.
const studentScheduleItem=student=>({id:`student-${student.id}`,name:student.name,age:student.age,level:student.level,topic:student.homework?`ДЗ: ${student.homework}`:'Индивидуальное занятие',num:'У',colors:['#b07adf','#7250a5'],isStudent:true});
let rawGroups=groups;
function enableStudentLessonLookup(){
  if(groups?.__withStudents)return;
  rawGroups=groups;
  groups=new Proxy(rawGroups,{get(target,property,receiver){if(property==='__withStudents')return true;if(property==='find')return predicate=>target.find(predicate)||students.map(studentScheduleItem).find(predicate);return Reflect.get(target,property,receiver)}});
}
enableStudentLessonLookup();
function renderScheduleParticipants(){
  const entries=[...rawGroups.map(group=>({...group,isStudent:false})),...students.map(studentScheduleItem)];
  $('#scheduleGroupList').innerHTML=entries.slice(0,8).map(entry=>`<div><i style="background:${entry.colors?.[0]||'#00d884'}"></i><span><strong>${esc(entry.name)}</strong><small>${entry.isStudent?'Ученик':'Группа'} · ${esc(entry.age||'')} ${esc(entry.level||'')}</small></span><b>${lessons.filter(lesson=>String(lesson.groupId)===String(entry.id)).length}</b></div>`).join('');
  $('.schedule-groups h3').textContent='Группы и ученики';
}
const openLessonForStudentsBase=openLessonForm;
openLessonForm=function(lesson,date){
  openLessonForStudentsBase(lesson,date);
  const selected=lesson?.groupId||$('#lessonGroup').value;
  $('#lessonGroup').innerHTML=`<optgroup label="Группы">${rawGroups.map(group=>`<option value="${group.id}">${esc(group.name)}</option>`).join('')}</optgroup><optgroup label="Индивидуальные ученики">${students.map(student=>`<option value="student-${student.id}">${esc(student.name)} · ${esc(student.level)}</option>`).join('')}</optgroup>`;
  if(selected)$('#lessonGroup').value=String(selected);
  const label=$('#lessonGroup').closest('label');if(label?.firstChild)label.firstChild.nodeValue='Группа или ученик';
};
const renderScheduleForStudentsBase=renderSchedule;
renderSchedule=function(){renderScheduleForStudentsBase();renderScheduleParticipants()};
const renderCalendarForStudentsBase=renderCalendarView;
renderCalendarView=function(){renderCalendarForStudentsBase();renderScheduleParticipants()};
$('#groupForm').addEventListener('submit',()=>setTimeout(()=>{enableStudentLessonLookup();rawGroups=groups.__withStudents?rawGroups:groups},0));
$('#cards').addEventListener('click',()=>setTimeout(()=>{if(!groups.__withStudents)enableStudentLessonLookup()},0));
if(view==='schedule')renderCalendarView();

// Recurring lessons with an explicit teaching period.
const lessonGrid=$('#lessonForm .form-grid');
lessonGrid.insertAdjacentHTML('beforeend',`<div class="recurrence-fields wide"><label>Повторение<select name="recurrence" id="lessonRecurrence"><option value="none">Не повторять</option><option value="mon-wed">Понедельник / среда</option><option value="tue-thu">Вторник / четверг</option><option value="custom">Другие дни</option></select></label><label id="repeatUntilLabel" class="hidden">Конец обучения<input name="repeatUntil" id="lessonRepeatUntil" type="date"></label><fieldset id="lessonWeekdays" class="weekday-picker hidden"><legend>Дни занятий</legend>${[['1','Пн'],['2','Вт'],['3','Ср'],['4','Чт'],['5','Пт'],['6','Сб'],['0','Вс']].map(([value,label])=>`<label><input type="checkbox" name="repeatDay" value="${value}"><span>${label}</span></label>`).join('')}</fieldset><p id="recurrenceSummary" class="recurrence-summary hidden"></p></div>`);
const recurrenceSelect=$('#lessonRecurrence'),repeatUntil=$('#lessonRepeatUntil'),weekdayPicker=$('#lessonWeekdays'),repeatUntilLabel=$('#repeatUntilLabel');
function academicYearEnd(startValue){const start=startValue?new Date(startValue+'T00:00:00'):new Date(),year=start.getMonth()<=4?start.getFullYear():start.getFullYear()+1;return isoDate(new Date(year,4,31))}
function selectedRepeatDays(){return [...$$('#lessonWeekdays input:checked')].map(input=>Number(input.value))}
function updateRecurrenceFields(){
  const recurring=recurrenceSelect.value!=='none',presets={'mon-wed':[1,3],'tue-thu':[2,4]};
  repeatUntilLabel.classList.toggle('hidden',!recurring);weekdayPicker.classList.toggle('hidden',!recurring);$('#recurrenceSummary').classList.toggle('hidden',!recurring);
  if(presets[recurrenceSelect.value])$$('#lessonWeekdays input').forEach(input=>input.checked=presets[recurrenceSelect.value].includes(Number(input.value)));
  if(recurring&&!repeatUntil.value)repeatUntil.value=academicYearEnd($('#lessonForm').elements.date.value);
  if(recurring){const names=['воскресеньям','понедельникам','вторникам','средам','четвергам','пятницам','субботам'];$('#recurrenceSummary').textContent=selectedRepeatDays().length?`Каждую неделю по ${selectedRepeatDays().map(day=>names[day]).join(' и ')}`:'Выберите хотя бы один день'}
}
recurrenceSelect.addEventListener('change',updateRecurrenceFields);weekdayPicker.addEventListener('change',()=>{if(recurrenceSelect.value!=='custom')recurrenceSelect.value='custom';updateRecurrenceFields()});
$('#lessonForm').elements.date.addEventListener('change',e=>{if(recurrenceSelect.value!=='none')repeatUntil.value=academicYearEnd(e.target.value)});
const openRecurringLessonBase=openLessonForm;
openLessonForm=function(lesson,date){
  openRecurringLessonBase(lesson,date);recurrenceSelect.value='none';repeatUntil.value='';$$('#lessonWeekdays input').forEach(input=>input.checked=false);updateRecurrenceFields();
  const dateLabel=$('#lessonForm').elements.date.closest('label');if(dateLabel?.firstChild)dateLabel.firstChild.nodeValue=lesson?'Дата':'Начало занятий';
};
$('#lessonForm').addEventListener('submit',e=>{
  if(recurrenceSelect.value==='none')return;
  e.preventDefault();e.stopImmediatePropagation();
  const form=e.currentTarget,data=Object.fromEntries(new FormData(form)),days=selectedRepeatDays(),start=new Date(data.date+'T00:00:00'),end=new Date(data.repeatUntil+'T00:00:00');
  if(!days.length){toast('Выберите дни занятий');return}if(!data.repeatUntil||end<start){toast('Укажите корректную дату окончания');return}
  const seriesId=Date.now(),created=[];for(let date=new Date(start);date<=end;date=addDays(date,1)){if(!days.includes(date.getDay()))continue;const lessonDate=isoDate(date);created.push({id:`${seriesId}-${lessonDate}`,seriesId,groupId:data.groupId,date:lessonDate,time:data.time,duration:data.duration,color:data.color,note:data.note})}
  lessons.push(...created);persist();renderCalendarView();$('#lessonDialog').close();toast(`Добавлено занятий: ${created.length}`);
},{capture:true});

// Complete backup and restore for moving data between local and published sites.
$('#exportBtn').addEventListener('click',e=>{
  e.stopImmediatePropagation();
  const backup={version:2,exportedAt:new Date().toISOString(),groups:[...rawGroups],students,resources,favorites,tasks,dayTasks,lessons,examDate};
  const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`teaching-hub-backup-${isoDate(new Date())}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);toast('Файл со всеми данными скачан');
},{capture:true});
$('#importInput').addEventListener('change',async e=>{
  e.stopImmediatePropagation();const file=e.target.files[0];if(!file)return;
  try{
    const data=JSON.parse(await file.text());
    const recognized=['groups','students','resources','favorites','tasks','dayTasks','lessons'].some(key=>Array.isArray(data[key]));
    if(!recognized)throw new Error('unknown-format');
    if(Array.isArray(data.groups))groups=data.groups;if(Array.isArray(data.students))students=data.students;if(Array.isArray(data.resources))resources=data.resources.map(resource=>({...resource,collection:'materials'}));if(Array.isArray(data.favorites))favorites=data.favorites;if(Array.isArray(data.tasks))tasks=data.tasks;if(Array.isArray(data.dayTasks))dayTasks=data.dayTasks;if(Array.isArray(data.lessons))lessons=data.lessons;if(typeof data.examDate==='string')examDate=data.examDate;
    rawGroups=groups;enableStudentLessonLookup();persist();renderGroups();renderStudents();renderResources();renderProgress();renderHome();if(view==='schedule')renderCalendarView();
    const total=rawGroups.length+students.length+resources.length+lessons.length;toast(`Импорт готов: ${total} записей`);
  }catch(error){toast('Этот файл не подходит. Скачайте новую копию')}
  e.target.value='';
},{capture:true});

window.teachingHubCloud={
  snapshot:cloudSnapshot,
  apply(data){
    if(Array.isArray(data.groups))groups=data.groups;if(Array.isArray(data.students))students=data.students;if(Array.isArray(data.resources))resources=data.resources.map(resource=>({...resource,collection:'materials'}));if(Array.isArray(data.favorites))favorites=data.favorites;if(Array.isArray(data.tasks))tasks=data.tasks;if(Array.isArray(data.dayTasks))dayTasks=data.dayTasks;if(Array.isArray(data.lessons))lessons=data.lessons;if(typeof data.examDate==='string')examDate=data.examDate;
    rawGroups=groups;enableStudentLessonLookup();persist();renderGroups();renderStudents();renderResources();renderProgress();renderHome();if(view==='schedule')renderCalendarView();
  },
  toast
};
